### ISSUE TITLE
Create a separate database for user profiles 

### ISSUE THREAD

**Issue by DanaAbuAli** [jihjihk/charlietable#35]

**Comment by DanaAbuAli** [comment]
pull up the information we get from the user object returned from firebase

**Comment by jihjihk** [comment]
# Fields
* City (UAE locations eg Al Khalidiya, Saadiyat)
* Interests (array with values as in InterestMultiSelect.js)
* Age group
* Gender
* Language(s)
* Occupation

**Comment by jihjihk** [comment]
### React-Select Documentation
https://github.com/JedWatson/react-select
