### ISSUE TITLE
Work on the matching algorithm 

### ISSUE THREAD

**Issue by DanaAbuAli** [jihjihk/charlietable#6]
For each event, we're giving the user a matching percentage based on their profile and previous preferences

**Comment by Seongun** [comment]
I'm taking this on.

Criteria:

(User Visible)
Location
Age
Meal type
Gender
Language
Preferred Time
_____________
(User Survey)
General interest,
hobbies,
organizations (job industry)
political leanings?
religions?

We will create a limited number of events, or let users create a couple. For each event within vicinity, we will calculate each user's % match to the specific event. How much we weigh each of these individual criterion will change as time goes by based on user's experience.
